/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : ContactId,
  'service_interest' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'submitted_at' : Timestamp,
});
export const ContactInput = IDL.Record({
  'service_interest' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'listContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func([ContactInput], [ContactSubmission], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : ContactId,
    'service_interest' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'submitted_at' : Timestamp,
  });
  const ContactInput = IDL.Record({
    'service_interest' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'listContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func([ContactInput], [ContactSubmission], []),
  });
};

export const init = ({ IDL }) => { return []; };